apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-BUILDNO
  labels:
    app: ruby
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby
      version: v1
  template:
    metadata:
      labels:
        app: ruby
        version: v1
    spec:
      volumes:
      - name: db-volume
        configMap:
          name: db-config
      containers:
      - name: ruby
        image: DIMG
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /config/
            name: db-volume