apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: ruby-rails-deployment
    namespace: default
  spec:
    maxReplicas: 10
    minReplicas: 1
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: ruby-rails-deployment
    targetCPUUtilizationPercentage: 50
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""