apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruby
  name: ruby-svc
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
  selector:
    app: ruby
    version: BUILD_VERSION
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.226.234.164